server:
  port: 9527
spring:
  application:
    name: cloud-gateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh # 路由id 没有固定规则要求唯一
#          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getOrd/** # 断言 路径相匹配的进行路由
            - After=2023-06-25T21:45:23.586+08:00[Asia/Shanghai]
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2023-06-24T21:45:23.586+08:00[Asia/Shanghai]



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
